[package]
name = "systemd_compose"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systemd_schema = { git = "https://github.com/Aposhian/systemd-schema" }
